### ISSUE TITLE
"gno serve"

### ISSUE THREAD

**Issue by moul** [gnolang/hackerspace#23]
Introducing Gno's "serve" Subcommand and Content Import/Export:

Use `gno serve` to start a local Gnovm server with Gnoweb for testing and development without a real blockchain.

For easy progress management:
- Export content: `gno export [filename.md]` to save server content.
- Import content: `gno import [filename.md]` to resume work from imported content.

Seamlessly migrate to a live blockchain when needed. Simplify your development with Gno's powerful features.

### Suggested flow

- start `gno serve`
- add your contract
- interact
- then, `gno export > tx.md`
- and, `gno import < tx.md`

Addresses https://github.com/gnolang/gno/issues/972
Depends on https://github.com/gnolang/gno/pull/1016

**Comment by thehowl** [comment]
Catching up on old convos.

Is this not addressed by `gnodev`?
