### ISSUE TITLE
Gnochess

### ISSUE THREAD

**Issue by moul** [gnolang/hackerspace#31]
Original Proposal: https://github.com/gnolang/gno/issues/611#issuecomment-1474224329

## Project Overview:
The Gnochess project aims to create a comprehensive example within the Gno ecosystem, building upon the discussions held during EthCC Paris. The primary objective is to develop a functional Gnochess product that serves multiple purposes and showcases the capabilities of the Gno platform.

## Key Objectives:
1. **Comprehensive dApp:** Create an end-to-end decentralized application (dApp) called Gnochess, which goes beyond markdown rendering. This dApp should encompass a dynamic web interface, potentially extending later to include a mobile app and CLI through an accessible API.

2. **User-Centric Design:** Prioritize usability and a positive user experience for individuals unfamiliar with web3 technologies. Implement features such as an automatic faucet mechanism to streamline the onboarding process for non-web3 users.

3. **MVP for GopherCon US:** Develop an initial Minimum Viable Product (MVP) version of Gnochess in time for the GopherCon US event scheduled at the end of September. This MVP should highlight the core functionalities and provide a hands-on experience for attendees.

## Project Milestones:
- [x] ~Reserve the domain "Gnochess.com".~
- [x] ~Create a standalone repository to house the project's source code, documentation, and related assets.~ -> https://github.com/gnolang/gnochess
- [x] Craft the necessary smart contracts to power the Gnochess dApp, ensuring seamless interactions and transactions.
- [x] Design and develop the web application, focusing on a user-friendly interface and smooth navigation.
- [x] Set up production and pre-production environments to facilitate testing and deployment.
- [ ] Bonus: redirecting from "chess.gno.land" to the Gnochess application.

**Comment by thehowl** [comment]
Closing this as we're tracking everything Gnochess on [its repo now](https://github.com/gnolang/gnochess/issues).

(I don't think we really have to redirect chess.gno.land to gnochess.com)
