### ISSUE TITLE
Chain activity visualizer

### ISSUE THREAD

**Issue by zivkovicmilos** [gnolang/hackerspace#55]
## Description

This idea, the same with #53, is something that's been on my mind for a few months now. We have tools in the gno ecosystem to sufficiently manipulate and extract transaction data (tx-archive, tx-exports, tx-indexer...).

It would be great to visualize this data somehow, similar to how [Mintscan visualizes IBC transactions](https://www.mintscan.io/visualization/ibc-network/). Of course, it doesn't need to be this sophisticated, but perhap the initial scope of the project can be:

- A user can see the most used Realms (bubble chart)
- A user can see the most imported Packages (userland / sys...) (bubble chart)
- A user can see interactions between Realms and Packages (graph, node interaction, similar to Mintscan)
- A user can pick an address and see interactions with Realms (isolated address, every realm)
- ...?

Looking for feedback
@ajnavarro @alexiscolin @waymobetta

**Comment by albttx** [comment]
Hey, 

Stargaze is already a cosmos chain, https://stargaze.zone, please use a different name to avoid any confusion.

FYI: i'm working on a `gnoland-exporter`, i will need to work on tendermint2 exporter too, and we'll have pretty graph on grafana.
Grafana will be internal and private, but i can also export a public grafana to show informations :)

**Comment by alexiscolin** [comment]
@zivkovicmilos I really like this idea. We should start thinking about it. @AidarItkulov @leohhhn

**Comment by zivkovicmilos** [comment]
Migrated to https://github.com/gnolang/gno/issues/3352
